backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: home
    extension: json
    format: json
    label: Home Page
    folder: _cms-data/home-page
    create: false
    identifier_field: name
    fields:
      - { label: bannerTitle, name: Banner title, widget: "string", required: true }
