backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: home-page
    extension: json
    format: json
    label: Home Page
    folder: _cms-data/home-page
    create: true
    identifier_field: name
    fields:
      - { name: title, label: Banner title, widget: string, required: true }
      - { name: image, label: Banner image, widget: image, required: true }
      - { name: introTitle, label: Intro title, widget: string, requires: true }
      - { name: description, label: Intro description, widget: string, requires: true }
      
